### ISSUE TITLE
Peer-to-Peer Code Review : Daniel

### ISSUE THREAD

**Issue by DanielAD10** [rubydevi/the-korner-capstone#1]
- Firstly, I really like your work. Your javascript code and css code are simple and clean so it's really understandable.
- In the menu, I think the menu lists should be placed align left instead of align center. 
- And the background color of menu, I think the color should be more bold. It'll look your menu more stylish and beautiful.It's my opinion.

**Comment by rubydevi** [comment]
Thanks for your feedback, I will look into it.
